server:
  port: 7002

eureka:
  instance:
    hostname: eureka-7002.com #eureka服务端实例名
  client:
    fetch-registry: false #表示自己就是注册中心，只需要维护实例即可
    register-with-eureka: false #eureka不需要将自己注册进去
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka/,http://eureka-7003.com:7003/eureka/  #对外暴露eureka客户端注册地址

