server:
  port: 9900
spring:
  application:
    name: microcloud-zuul

eureka:
  client:
    service-url:  #将库存服务注册进 eureka 服务内
     defaultZone: http://eureka-7001.com:7001/eureka/,http://eureka-7002.com:7002/eureka/,http://eureka-7003.com:7003/eureka/
  instance:
    instance-id: microcloud-zuul-9900
    prefer-ip-address: true

zuul:
  routes:
    microcloud-stock: /myproduct/**
#    myproduct.serviceId: microcloud-stock
#    myproduct.path: /myproduct/**
  ignored-services: "*"

