server:
  port: 8001
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  aop:
    proxy-target-class: true
  application:
    name: microcloud-stock-${server.port}

eureka:
  client:
    service-url:  #将库存服务注册进 eureka 服务内
     defaultZone: http://eureka-7001.com:7001/eureka/,http://eureka-7002.com:7002/eureka/,http://eureka-7003.com:7003/eureka/
