server:
  port: 8001
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  aop:
    proxy-target-class: true
  application:
    name: microcloud-stock-${server.port}

eureka:
  client:
    service-url:  #将库存服务注册进 eureka 服务内
     defaultZone: http://localhost:7001/eureka
